language: node_js
node_js:
  - "12"
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 'm9qnE22yrb/fclh7DjPrLNtQmdBi76VmqxSK21uc9igD/S1COOcu4wo0Th0LLgLNtZ614JTVggq+4QkpheItRUierafgtbxWlXlYtI4GDXVMUDmaPPFtVxDgklRLRAlhzhtHlUMq7M+Mc2DbsbabynUQ6Wb9aJM5MBC+52qkhdfKeQ6KYFV+NZMjJH7bKixI76IF+c6q9ctX3B0yJGhd2zamOZENMUBRiSrJ/4p0emhS1MD6RIk9/+RwWa1CKYVteIbhY4b38tQjDza0CsITXHZlpn4Vy6OT8ouQdaAAdV5cYzYeVc468nN2EzGevhc01hX22Cdfu+FdhdeJ79qxFYjFUnqiPnGolOoO40BsvFFej0/ixJMJW2UBI7vWzr2e0kmzM0s4ykHBjJFpAym0Yge/NCKSHjVTNdIwZsQit/geiOmXuRiQQ5rEWn2+Mm3aZo7EZZVSBHEf6rfZfij5Vp31qOEwO9giWe9FpjDc4XjTS2yqvwIkH+VC9S6EM92YNRZsOJapwTcGZVuIZbRE/vyGy7rnFlhnrSyx9SVPicfRlWSG5AOECgh5OOWngfpDyAxm9vdG4X7v6KKqWlp+wl/QRcUbZsfxnoUbrx72jZiaBB1dHFzDzT10JhMXhOgLcM9hddvTE1+GBJ7CGCV4RILM7hKcLqjCKHb77PP1sa0='
  project: dev
