language: node_js
node_js:
  - '12'
cache: npm
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
  - npm i -g firebase
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  provider: firebase
  token:
    secure: 'Fayb/az+muClEDwnUU/+y+/uFe2ceBrVbRf5+f0ct3VA5IoulNsTBjJMAI5HbBrxlWmFaCuKojVfjzDb7IxmZ/7DD+l+szkRgHGtFdSINZAn1rB+2rIPejVz6bpW2T1VStefP6wFmqPqIzTdXN5M6HvgJjj3RmXVikjsN+TDmnZ6frA3WTa5B9OEAHGuOIDqi1UDT9RocTXqbaYOgNDEZg+kMdEzL1avArj8C/0Qr6UrOHaUsrz+dx0iNd50iWepEtKn71MhzxT/mpjS8Uni8PGTXCeRiQz2WQVOQOHwIUwj2cgwU193QpTESK1Ij3DNmlQtp9FOjH11nbHK4TWshl0v2xqhTHH5nj6XFZpJU8f26sgFjJUQiVO8VwEK0HxLfJW12obSJF/xk98EVbRkIe26kgvqOXzolXbkySJLO1MU4GUCpFuOdksfHtIBcgTHW2/Et/qAyDs22T6keX+dRxMiLk4C3ANfRpk+D2lg+fRORfGMg0l2BF9kX1v0gh+jTTPt/yCezdaqAeW3d1JqSZErBL/fc9cgsTz9f1aW5SzL234EuzHd0Dos+W88GRnk+gbW0/b817SWtswbGzdwayykshom93WlyI7o7VnW4ziuDYFhbJeCeDvfghUrORnfSFvc34+b2iAAWFamRIe4iPnhjS+3JPcaFSLbTqtN1PM='
  project: 'dragonhacks-web'