language: node_js
node_js:
  - stable
  - '8'
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  - provider: firebase
    skip_cleanup: true
    project: dev
    on:
      branch: develop
      repo: drexelieee/dragonhacks-frontend
      node: stable
  - provider: firebase
    skip_cleanup: true
    project: prod
    on:
      branch: master
      repo: drexelieee/dragonhacks-frontend
      node: stable
