language: node_js
node_js:
  - '12'
cache: npm
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  provider: firebase
  token:
    secure: 'B6REbpIZR/j0KpTMURCsi28JRBtwPMkEvOcRrkA8SRkbuBAZ7RMcCRG2eyZlhmUurSXVltQMJJ5BXf+jfjejJR1PeFiWOa4EC3UL8HtTQ/DUimIoitCHhDm+K6QPRSRISyFJ2jJvTT+YeyK1bE2Dw+dZnHC+qDIy8w+7FBWlQk/fiWDgyf2C4z2TpwWOeB8JBBREGqplUbeC61lPlrlCQ5HB/FVM3HOfDOZf97QuK/DcnaZhb36rgu/DKrY6HMJ/Ma5+q/H/eX5cbmnzNjHLAIo89/vsUqHIfmAASYO3871c4k+dQ9WyS2GxvwKkaBqAcIV5ojKvYYh8632WbWN6AZnwB6D6e9nVSGb8/gzd8KY50Bhv8N9rseTTuRDeC74CbjMU/29jP6/AdS+boc0U4otuvuhw4vBlIjpIVnGRGTnxr1fRXHbx2ZNX1K9Z4d8xnZVoAfMdn9UNb7B97JBkA8vgIQkvjRqiZOzeCICwuCxIZoOMaMNqC6RhNAb8CxjaSCk1Xqu6bK94P/t+v4hOXBGH31nG18bh2oetfJV+aFyIE16Vqz/etpQaEP2XVm09LXjXP0arPAxKyCtxtV0R3+HfEup2duMmW3MzeZgZt0fWHvVZ4B60b1bj2FXqiRuN2yGTR9L6BlkbKl8JnqxNdUZS5flUUqr1cJt0i+Jt3pQ='
  project: 'dragonhacks-web'