language: node_js
node_js:
  - '12'
cache: npm
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  provider: firebase
  token:
    secure: 'EusS8U9NYhimQ4mBBeuyqt/lcAKgMmd1k7Dxq3EGgfcxY7YHFRKZutJLKnewVIDRX9B5tPp78vf1EP7G3f+OBQezteDEXvVIdYOjQ3JnQvQUYDr/wIP8nPmz0kK/SNB0mKo+oV6hZBEs+ASLNd+H60zIuVbI0sM+JMiUfdkcITw1Urp9PvIT6mojhCSQnGSoG71BbFqJ0zI81Gd0xkZfMf5QIsryPatV35imC2qrw0lFQUx3/vM/nT034cHq0BEs20ujzX6E9VRvXtCr4gE+TKleLl90+yBclvvANm8IlucEDg5cffyCcwHGa8bZVrHsq8lSo0a2x2zPmfx4Nnh5IDtJ2wHs/r32rdusmJ3Dr1NByOGc9r7LSXvcPvWZ4BPIEejdDU73bEdhoUhdn3qwvSD0r0NZ8+tCCc5D0sb2zYYAc9i2HYYGy4wTY9eCJPz6XDoKMWStG4Bk8VZp9mPlE83adJnzGlmuezfAknCPJkKmJkAr+e7OLgnOtjQ1eD6Rr/5vCEUpCkXc+Vh4DpCEVxJRBKOqhiFMI3wttYKkBpYJ77sGOaRYuE7/7bxcoInZzKkIhvdiZxlRi6PAL6fRG06g6fqJYO4wLtV7Sb7I1EItMqgAT07ccX+iwjWp8QIGQQz2R2hjferIMfa0NNRDM4abgpNQplDwrgb7bzCm0+k='
  project: 'dragonhacks-web'