language: node_js
node_js:
  - '8'  # Recommended deploy version
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
install:
  - npm ci
  - cd functions
  - npm ci
  - cd ..
script:
  - npm run build
  - npm run lint
  - npm test
  - cd functions
  - npm run build
  - npm run lint
  - npm test
  - cd ..
deploy:
  - provider: firebase
    skip_cleanup: true
    project: dev
    on:
      branch: develop
      repo: drexelieee/dragonhacks-web
      node: '8'
  - provider: firebase
    skip_cleanup: true
    project: prod
    on:
      branch: master
      repo: drexelieee/dragonhacks-web
      node: '8'
