language: node_js
node_js:
  - '12'
cache: 'npm'
branches:
  only:
    - master
    - develop
before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools
script:
  - npx standard
  - npm run build
  - npm test
deploy:
  provider: firebase
  token:
    secure: 'kT4o3sgLH5qa6BgLtTTlA1Nt/ZaV9deOj96aYTPUjnngH40W6rKD+D7K4orwSqAfXBqil1pwYuaxo1RoC0oB9DcuBkkjNX8um1AaNuN1RUiNDD1pBf8XvEJT7HkVo8jOGSSImbPgqbDFxB3dEU+kDke6D0lbUj2/sdM1qvMmNO6t+oDkHpKZ9fcQLr/M0607uiijULPcbhTP4NFSXqeKTrZ57H5A4elSBLj4jb1phU9j8uF0GfPWPUm9M3wSxQD31Pi/G+/2BdbYZR8M4mmZ5tQOjf/icXpg0JZ4l3uBkKxgNoJjaM9adyFUpXESsFWkiiFu1IRilyvUY7ZYG7mTY5WQZtmK0R4AOdnEE/Ri1ewwTjvzgZW/peGV6DpKJ62OqfxvIXtPj7lFGTeDarkoigp2aylXdCBUfkNBKygsReiGYwqBrbdx29KsUW2O7gdUMvyHMSokqMvzSx9hV6FZXnKw9sh84YiDYQC1y0nq6aBh0td1MdJYZcZR84jBLn3RDaAAIOXgzm6t9vRZ4tauy46h9o914JVEJaKvzJKYDtOY+alKwAgFhkf6nOAGbccvZxord7LG0VhiSs+qHIgnmV0KuuLh3+JiAw/RtZvjJ/3Qr5pef4C/iyc+zkwsMRFqcZbNgRSqx8MuiIKGm8/5sluS9dceTv5FBydxlmDmehE='
  project: prod
# after_success:
#   - firebase --token "${FIREBASE_TOKEN}" login
#   - firebase --token "${FIREBASE_TOKEN}" use prod
#   - firebase --token "${FIREBASE_TOKEN}" deploy
# env:
#   global:
#     secure: OBzihYa/al8gy+it3S8k53mPSxLWKB1YLkllm435Z0FjyHHEJvOCJAom+WjofYbN3nARMwnNcKGUVvrT5FFoJAtqhnVFAG+HB+uckOM4xpZ2rA4gHMu3zBmEP9QHj+W5tYRwnPeVv/DV2m7XtfVgqCOLQPyZuck7pPXNiDJYzoZFEGfs5DvOOmryePardCJ97f53tz3yrPW06YBURJESKfRTv+M3zUIXFoYyxN8nx4XXH62f1YPFcEj2/oTLBeWdTMEZ1CHep+xS2G849rr6Gw9GQQ22p+hg5cK5nINlEb3FZSy4nQDtt03NFJCnADcqbj+PY1jsTIW+hcDoePC2HWEoOC1HlmyNywOXXNyHdxVaEprnt/wCl08WnSZIMrAabccsbGfQy6ys1iQczhT1QMHj5MPq3g0wPFGx/snymYkoz+VSIZHoSrvVj+C95vz+oah4/wSrBBhMmL8Do/EwLQOVfKW86utztK2MbhySylNhOClAHBP0WVo73TCzifj7QF9i4VUmeFHPXtFqNhP7NIQCkG2QpFI0qmydP1skZeP8b7nkLRt3BMi4Rr7Lng8DTgG5wtgsLX2NQWjYgnTvERjjPO8ardw7GripidR8dKFEjZa1EiqxlfWlmr1URSfxDLzrR/z09hHZkoWagRBcP1siiI56ALHkwc1TvCfJbas=
